### ISSUE TITLE
Mac Issue - TF2 Classic (Version 2.0.0)

### ISSUE THREAD

**Issue by crazygamer113** [danielmm8888/TF2Classic#164]
Recently I have attempted to install TF2 Classic on Mac and after downloading the game from the website and putting the game into Source Mods and completing the install of Source Multiplayer 2013 followed by setting the beta to Upcoming. I have received the error: http://i.imgur.com/vw0EwQs.png followed by and Crash error for HL2! If I have missed something please do tell me or if this can be fixed that would be great.

**Comment by danielmm8888** [comment]
The reason why you're seeing this is because 2.0.0b1 does not ship with the OS X binaries.
While OS X compilation does work, connecting to a server using those binaries simply gives you an insecure error.

This same error is referenced here:
https://github.com/ValveSoftware/source-sdk-2013/issues/279
However, nobody seems to have actually found a solution for it.

**Comment by crazygamer113** [comment]
Alright thank you for your response Hopefully sometime soon someone will be able to find the solution! :)

**Comment by 404UserNotFound** [comment]
solution: install windows
