### ISSUE TITLE
Can download the auto updater

### ISSUE THREAD

**Issue by roydbtR** [danielmm8888/TF2Classic#172]
The website is down

**Comment by Th13teen** [comment]
Hi roydbtR,

The website is down due to a security issue within the source engine, The team are hard at work and the game will be playable again shortly.

Valve has patched the version of the engine we use but haven't fully patched CS:S, HL2:DM and DoD:S yet.

The website, downloads and game itself will be up again soon(tm)

**Comment by danielmm8888** [comment]
The downloads have been put back up, however we're working on a new auto-updater.

**Comment by EmilSayahi** [comment]
Can you close this issue?
